/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import scene from '../assets/3d/ground.glb'

export function Ground(props) {
  const { nodes, materials } = useGLTF(scene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, 1, -1.442]}
        scale={[5, 2, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={nodes.Plane_1.material}
        position={[0, 0, -0.473]}
        rotation={[-1.567, 0, 0]}
        scale={[5, 2, 1]}
      />
    </group>
  );
}

